### ISSUE TITLE
System.Drawing removed on all operating systems except Windows

### ISSUE THREAD

**Issue by ahouts** [mxgmn/MarkovJunior#3]
When trying to run `Program.Main` on Linux with `net6.0` I get an exception.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'GUI' threw an exception.
 ---> System.PlatformNotSupportedException: System.Drawing is not supported on this platform.
   at System.Drawing.Bitmap..ctor(String filename)
   at Graphics.LoadBitmap(String filename) in /home/ahouts/Projects/MarkovJunior/source/Graphics.cs:line 12
   at GUI..cctor() in /home/ahouts/Projects/MarkovJunior/source/GUI.cs:line 29
   --- End of inner exception stack trace ---
   at GUI.Draw(String name, Branch root, Branch current, Int32[] bitmap, Int32 WIDTH, Int32 HEIGHT, Dictionary`2 palette)
   at Program.Main() in /home/ahouts/Projects/MarkovJunior/source/Program.cs:line 67
```

Unfortunately Microsoft has decided to remove `System.Drawing` on all operating systems except Windows.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by ahouts** [comment]
> Does it build on net5.0?
> 
> For macOS, a user posted a [workaround](https://old.reddit.com/r/proceduralgeneration/comments/v2go7t/i_looked_at_a_lot_of_modern_architecture_and_made/iatys4t/).
> 
> I'll remove the `System.Drawing` dependency then.

It should work on `net5.0` since the api was removed starting in `net6.0`. I implemented Microsoft's recommended fix in #4, so feel free to use that if you like.
